[kubernetes]
enable = true
[kubernetes.hostPort]
max_port = 9000
min_port = 8000

[alibabacloud]
enable = true
[alibabacloud.slb]
max_port = 700
min_port = 500

[volcenginecloud]
enable = true
[volcenginecloud.clb]
max_port = 65535
min_port = 1
